<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <DefineConstants>$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.MCM.Abstractions\Crest.MCM.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.MCM.Common\Crest.MCM.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Crest.MCM.Bannerlord" />
  </ItemGroup>

</Project>