using HarmonyLib;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

using TaleWorlds.Library;

namespace Bannerlord.Harmony;

/// <summary>
/// Phase R.2 -- modder-facing live patch inspector. Writes a complete snapshot
/// of every Harmony-patched method (by every Harmony instance loaded into the
/// process), grouped by target type, with full per-patch metadata, to a
/// timestamped file under <c>Modules\CREST\patches-snapshot-yyyyMMdd-HHmmss.log</c>.
///
/// Triggered two ways:
/// <list type="bullet">
///   <item><c>Ctrl+Alt+P</c> while the game window has focus -- bound in
///         <see cref="SubModule.OnApplicationTick"/>.</item>
///   <item>The "Export Snapshot" button in the imgui DebugUI panel
///         (Ctrl+Alt+H to open).</item>
/// </list>
///
/// The snapshot is intended to be attached to bug reports. It tells whoever
/// is debugging the user's mod stack:
/// <list type="bullet">
///   <item>Which TaleWorlds method each patch targets.</item>
///   <item>Which Harmony id owns each patch (so a "BloodMod1313" patch is
///         distinguishable from a "Bannerlord.Harmony" patch).</item>
///   <item>Patch priority and before / after constraints, which is what
///         determines patch ordering when multiple mods touch the same method.</item>
/// </list>
///
/// Pairs with the <c>Crest-Doctor.ps1</c> PowerShell tool, which can be invoked
/// with <c>-IncludePatchSnapshot</c> to bundle the most recent snapshot file
/// into its diagnostic report.
///
/// Why a separate file rather than appending to <c>runtime.log</c>: the snapshot
/// is large (hundreds of patches in a real install with mods), the file format
/// is structured (one method per block, multi-line per patch), and modders need
/// a clean copy to attach to issue reports without bringing along the rest of
/// our diagnostic noise.
/// </summary>
public static class CrestPatchSnapshot
{
    private const string Source = nameof(CrestPatchSnapshot);

    /// <summary>
    /// Capture a snapshot of every patched method in the current process and
    /// write it to a timestamped file. Returns the absolute path on success
    /// or <c>null</c> on failure (e.g. write permissions, disk full). Failures
    /// are logged via <see cref="CrestDiag"/> but do not throw -- this method
    /// is safe to call from a hotkey handler.
    /// </summary>
    public static string? Capture()
    {
        try
        {
            var moduleRoot = ResolveModuleRoot();
            if (moduleRoot == null)
            {
                CrestDiag.Log(Source, "could not resolve Modules\\CREST root; aborting");
                return null;
            }

            var ts = DateTime.Now.ToString("yyyyMMdd-HHmmss");
            var path = Path.Combine(moduleRoot, $"patches-snapshot-{ts}.log");

            var report = BuildReport();
            File.WriteAllText(path, report);
            CrestDiag.Log(Source, "snapshot written to " + path);
            return path;
        }
        catch (Exception ex)
        {
            CrestDiag.LogCaught(Source, "Capture", ex);
            return null;
        }
    }

    /// <summary>
    /// Build the full report string. Public so tests / future tooling can
    /// invoke it without writing to disk.
    /// </summary>
    public static string BuildReport()
    {
        var sb = new StringBuilder(64 * 1024);
        var allPatched = HarmonyLib.Harmony.GetAllPatchedMethods().ToList();

        // ----- Header -----
        sb.AppendLine("# CREST patch snapshot");
        sb.AppendLine("# Generated by CrestPatchSnapshot (Phase R.2 in-game inspector).");
        sb.AppendLine("# Attach this file to bug reports involving Harmony patches in CREST.");
        sb.AppendLine("# ");
        sb.AppendLine($"# Captured at:           {DateTime.Now:yyyy-MM-dd HH:mm:ss zzz}");
        sb.AppendLine($"# Process:               {Path.GetFileName(System.Diagnostics.Process.GetCurrentProcess().MainModule?.FileName ?? "?")}");
        sb.AppendLine($"# .NET runtime:          {Environment.Version}");
        sb.AppendLine($"# OS version:            {Environment.OSVersion}");
        sb.AppendLine($"# Total patched methods: {allPatched.Count}");

        var harmonyVersion = SafeGet(() => typeof(HarmonyLib.Harmony).Assembly.GetName().Version?.ToString() ?? "?");
        sb.AppendLine($"# Harmony version:       {harmonyVersion}");

        // Game version (best-effort; exposed via TaleWorlds.Library if available)
        var gameVer = SafeGet(() => ApplicationVersion.FromString(
            typeof(ApplicationVersion).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion ?? "")
            .ToString());
        if (!string.IsNullOrEmpty(gameVer)) sb.AppendLine($"# Game build:            {gameVer}");

        sb.AppendLine();

        // ----- Loaded module list -----
        sb.AppendLine("# Loaded modules (from BUTR.Shared.ModuleInfoHelper)");
        try
        {
            var modules = Bannerlord.BUTR.Shared.Helpers.ModuleInfoHelper.GetLoadedModules().ToList();
            foreach (var m in modules)
            {
                sb.AppendLine($"#   {m.Id,-40} {m.Version}");
            }
            sb.AppendLine($"#   ({modules.Count} modules total)");
        }
        catch (Exception ex)
        {
            sb.AppendLine("#   (could not enumerate modules: " + ex.GetType().Name + " " + ex.Message + ")");
        }
        sb.AppendLine();

        // ----- Patches grouped by declaring type -----
        sb.AppendLine("# Patched methods, grouped by declaring type");
        sb.AppendLine("# Format:");
        sb.AppendLine("#   <DeclaringType>");
        sb.AppendLine("#     <method signature>");
        sb.AppendLine("#       <prefix|postfix|transpiler|finalizer>  owner=<harmonyId>  priority=<n>");
        sb.AppendLine("#         method   = <patch declaring type>.<patch name>");
        sb.AppendLine("#         before   = [<harmonyId>, ...]");
        sb.AppendLine("#         after    = [<harmonyId>, ...]");
        sb.AppendLine();

        var byType = allPatched
            .GroupBy(m => m.DeclaringType?.FullName ?? "<unknown>")
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var typeGroup in byType)
        {
            sb.AppendLine(typeGroup.Key);
            foreach (var method in typeGroup.OrderBy(m => m.Name, StringComparer.Ordinal))
            {
                sb.AppendLine("  " + FormatMethodSignature(method));
                var info = HarmonyLib.Harmony.GetPatchInfo(method);
                if (info == null)
                {
                    sb.AppendLine("    (GetPatchInfo returned null)");
                    continue;
                }

                AppendPatches(sb, "prefix",     info.Prefixes);
                AppendPatches(sb, "postfix",    info.Postfixes);
                AppendPatches(sb, "transpiler", info.Transpilers);
                AppendPatches(sb, "finalizer",  info.Finalizers);

                // If all four were empty, surface that explicitly. We have
                // observed this case on patches applied by BLSE during the
                // launcher-process phase: GetAllPatchedMethods returns the
                // method but GetPatchInfo's lists come back empty in the
                // game process. Useful signal for triage.
                var hasAny = info.Prefixes.Any() || info.Postfixes.Any() ||
                             info.Transpilers.Any() || info.Finalizers.Any();
                if (!hasAny)
                {
                    sb.AppendLine("    (no patches reported by GetPatchInfo; method tracked by Harmony but lists are empty)");
                }
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void AppendPatches(StringBuilder sb, string kind, IEnumerable<Patch> patches)
    {
        foreach (var p in patches.OrderBy(p => p.priority).ThenBy(p => p.index))
        {
            sb.AppendLine($"    {kind}  owner={p.owner}  priority={p.priority}");
            var declaring = p.PatchMethod.DeclaringType?.FullName ?? "?";
            sb.AppendLine($"      method = {declaring}.{p.PatchMethod.Name}");
            if (p.before != null && p.before.Length > 0)
                sb.AppendLine($"      before = [{string.Join(", ", p.before)}]");
            if (p.after != null && p.after.Length > 0)
                sb.AppendLine($"      after  = [{string.Join(", ", p.after)}]");
        }
    }

    private static string FormatMethodSignature(MethodBase method)
    {
        var parameters = method.GetParameters();
        var args = string.Join(", ", parameters.Select(p =>
            (p.ParameterType.IsByRef ? "ref " : "") + p.ParameterType.Name + " " + p.Name));
        var returnType = (method as MethodInfo)?.ReturnType?.Name ?? "void";
        return $"{returnType} {method.Name}({args})";
    }

    /// <summary>
    /// Resolve <c>Modules\CREST\</c> on the user's install. Mirrors the path
    /// resolution used by <see cref="CrestDiag"/> (anchor on this assembly's
    /// location, walk up two parents from <c>bin\Win64_Shipping_Client</c>).
    /// </summary>
    private static string? ResolveModuleRoot()
    {
        try
        {
            var asmLoc = typeof(CrestPatchSnapshot).Assembly.Location;
            if (string.IsNullOrEmpty(asmLoc)) return null;
            var binDir = Path.GetDirectoryName(asmLoc);
            if (binDir == null) return null;
            var binParent = Directory.GetParent(binDir);
            if (binParent == null) return null;
            var crestRoot = binParent.Parent;
            return crestRoot?.FullName;
        }
        catch
        {
            return null;
        }
    }

    private static string SafeGet(Func<string> f)
    {
        try { return f() ?? ""; } catch { return ""; }
    }
}
